### ISSUE TITLE
Int to Nat

### ISSUE THREAD

**Issue by felixSchl** [pigworker/CS410-15#2]
Hey, I am just curious: is this correct? https://github.com/pigworker/CS410-15/blob/master/HaskellSetup.hs#L44.

Since we're shrinking the domain from that of all integers to that of all natural numbers, not all integers will find a point on the co-domain of this function. Should this not rather return `Maybe Nat`? It currently recurses forever if `n` is a negative integer to begin with. Or is this correct and we consider the non-termination to be the implicit bottom?

**Comment by pigworker** [comment]
Hi

On 20 Sep 2017, at 03:22, Felix Schlitter <notifications@github.com> wrote:

> Hey, I am just curious: is this correct? https://github.com/pigworker/CS410-15/blob/master/HaskellSetup.hs#L44.
> 
> Since we're shrinking the domain from that of all integers to that of all natural numbers, not all integers will find a point on the co-domain of this function. Should this not rather return Maybe Nat? It currently recurses forever if n is a negative integer to begin with.

Technically true for Integer, but not Int. Might take a while for Int, all the same.

> Or is this correct and we consider the non-termination to be the implicit bottom?

Given the way it's used in practice (to convert window dimensions and cursor
positions into Agda-manipulable values, rather than in general), it's not a big
deal.

I mean, it's not as if Haskell programmers routinely promise to tighten their
types only to the meaningful domain.

That file is intended as "glue code" between specific Agda exercises and the
outside world. If taken as directed, all will be well.

Wontfix

Conor

**Comment by felixSchl** [comment]
> I mean, it's not as if Haskell programmers routinely promise to tighten their types only to the meaningful domain.

If  we talk about partial vs. total functions then I would argue the opposite and would prefer a total function any day of the week even at the cost of less convenience somewhere else. I could always unleash my `fromJust` when providing a value to the function I know is in the range of natural integers.

Anyway, as I warned this was really just curiosity and I learned something from it. So case closed :)
